name = "conetwork"
main = "cloudflare-worker/proxy.js"
compatibility_date = "2025-12-01"

[vars]
VITE_FINANCE_API = "https://conetwork.klozti-com.workers.dev/api/finance/quote"
FINNHUB_ENV = "prod"
VITE_LLM_MODEL = "gemini-2.5-flash-lite"
VITE_LLM_PROVIDER = "gemini"
SUPABASE_URL = "https://pakkevrgjsbujsvvkgtw.supabase.co"
